### ISSUE TITLE
商店界面修改

### ISSUE THREAD

**Issue by huangjihui511** [huangjihui511/BUAA-2019-Good-Good-Study-Beta#21]
1. 加入轮播模块
2. 加入标签推荐

**Comment by Lonarch-zl** [comment]
1.标签推荐查看更多热搜内容可以丰富一点
2.轮播模块没有显示出来

**Comment by Lonarch-zl** [comment]
1.轮播模块图片无法点击进去
2.热搜界面的UI改进
3.标题的设计改进

**Comment by Lonarch-zl** [comment]
1.商店部分图片显示不出来
2.查看更多里面的右下角蓝色按钮显示问题
3.热搜图片点击进入后的界面问题
4.热搜关键词选择展示问题
