### ISSUE TITLE
引导用户使用经验

### ISSUE THREAD

**Issue by huangjihui511** [huangjihui511/BUAA-2019-Good-Good-Study-Beta#30]
1. 编辑上传增加经验
2. 新加入编辑功能
3. 统一的经验管理页面，和介绍

**Comment by gzhGit** [comment]
编辑功能、经验页面

**Comment by huangjihui511** [comment]
1. 相册选择和收藏选择 文字说明修改
2. 保存图片按钮位置
3. 滤镜的UI修改
4. 剪切图片的title

**Comment by huangjihui511** [comment]
双击改成单击

**Comment by notasadsong** [comment]
1、改动增加经验的前三个按钮点击事件为：toast提示框
2、”表情被收藏下载“按钮的bug修复

**Comment by gzhGit** [comment]
保留10个滤镜
