### ISSUE TITLE
加强表情和用户交互

### ISSUE THREAD

**Issue by huangjihui511** [huangjihui511/BUAA-2019-Good-Good-Study-Beta#31]
1. 统计自己图片被别人收藏或者点赞的数目（用标签实现）
2. 关注列表和被关注列表，更新的提示
3. 在图片详情页面添加公开按钮，并获取经验

**Comment by huangjihui511** [comment]
1. 点赞数和收藏数，可以使用tag
2. 列表页面可以美化，加入文字标题和列表形态等等
3. 从新的设置页面链接到关注和被关注页面

**Comment by huangjihui511** [comment]
点赞数和收藏数，可以使用tag

**Comment by huangjihui511** [comment]
上传和公开怎加经验 有弹出提示

**Comment by notasadsong** [comment]
关注按钮需要在相应位置点击一下才能出现

**Comment by huangjihui511** [comment]
已更新改成有更新

**Comment by notasadsong** [comment]
1、关注数字显示未实时更新
2、关注者为0时出现报错
