### ISSUE TITLE
增强标签和图片管理模块

### ISSUE THREAD

**Issue by huangjihui511** [huangjihui511/BUAA-2019-Good-Good-Study-Beta#4]
1. 用户可以自由的上传删除图片
2. 用户可以任意创建，删除，修改自己的标签
3. 用户可以对于表情任意的添加，修改，删除，创建标签
4. 可能需要新的上传页面等其他页面

**Comment by huangjihui511** [comment]
发现问题
1. 顶部导航栏没有采用模版中的导航栏
2. 点击标签拦右边加号后无法编辑
3. 编辑界面后退键后退不正常
4. 主页每一行只显示了两个表情
5. 点击选择之后全选，删除，取消按钮建议按照统一的UI设计的按钮板块设计
6. 本人尝试给一个表情添加新创建的标签，但是在这个表情的修改页面没有显示出来，可能是显示数量限制？建议使用UI的模块
7. 无法删除图片的某个标签
8. 修改标签页面返回地址不对
9. 添加标签等页面如果用户给一个表情添加多次一个标签会产生重复。
10. 大部分图片显示部分可以采用模版的方法

**Comment by notasadsong** [comment]
1、对一个图片修改标签后会新生成一个收藏的表情
2、在图片编辑的页面好像没有看到之前增加的标签（还是我没找到）
3、新加的标签和原来标签风格不同

**Comment by notasadsong** [comment]
从商店收藏的表情进入编辑模块无法显示

**Comment by huangjihui511** [comment]
主页的宽度有问题，导致在手机上可以左右移动

**Comment by huangjihui511** [comment]
还存在的问题
1. 主页的颜色和导航栏不搭配
2. 主页上的添加按钮可以换成模版中更精致的
3. 本人有一些表情删不了
4. 标签不知道怎么删除

**Comment by huangjihui511** [comment]
添加标签时连续点击添加会有很多个框
