### ISSUE TITLE
设置页面重新完成

### ISSUE THREAD

**Issue by huangjihui511** [huangjihui511/BUAA-2019-Good-Good-Study-Beta#41]
1. 使用模版
2. 增加经验改为使用aboutExp页面
3. 关注页面和被关注页面放在卡片相应位置

**Comment by notasadsong** [comment]
1、增加经验的前三个按钮好像没有点击事件
2、点击”其他方式“中的”表情被收藏下载“会报错

**Comment by notasadsong** [comment]
1、经验显示字体颜色看不清
2、本地改成“我”
