### ISSUE TITLE
推荐表情模块

### ISSUE THREAD

**Issue by huangjihui511** [huangjihui511/BUAA-2019-Good-Good-Study-Beta#5]
1. 根据搜索频率推荐关键词（推荐页面显示每个标签使用数量）
2. 更具使用表情频率推荐表情 （显示每个图片等使用数量）
3. 统计得到每个标签被搜索，每个图片被收藏，下载等数据。

**Comment by Lonarch-zl** [comment]
1.在使用部分表情后，“为你推荐”点击‘’查看更多没有表情推荐
2.推荐关键词部分的使用没有显示

**Comment by Lonarch-zl** [comment]
1.“查看更多”中“到头了”是指页面最后一面还是到底部了
2.查看更多里面的页面数始终只有一页
3.推荐表情没有更换过
