### ISSUE TITLE
商店的补充和修复

### ISSUE THREAD

**Issue by huangjihui511** [huangjihui511/BUAA-2019-Good-Good-Study-Beta#50]
1. 主页上的的自制推荐板块
2. UI重新设计
3. 根据主题自定义推荐
4. 轮播模块的内容

**Comment by huangjihui511** [comment]
自制推荐的文字可加入用户头像，点击进入用户的页面

**Comment by huangjihui511** [comment]
自制推荐的表情点击用户是开发者，（应该是豪哥）

**Comment by Lonarch-zl** [comment]
1.轮播模块中的表情风格可以换成差异较大的一组
2.自制表情推荐中同一用户上传的表情可以考虑放在一个版块中
