### ISSUE TITLE
beta 阶段测试bug

### ISSUE THREAD

**Issue by huangjihui511** [huangjihui511/BUAA-2019-Good-Good-Study-Beta#79]
每个团队把发现的bug分点写在这个issues中，至少每个小组提供10个（如果从现在的版本找不到就从以前挑选有代表性的。每个发现的bug配上是测试的什么模块。
比如：
1. 刷新页面：无法及时更新信息

**Comment by pyb19991125** [comment]
现有的：
1.商店中的自制表情推荐出现undefined用户
2.打开本地界面报错
![image](https://user-images.githubusercontent.com/50090686/83583913-36aa2400-a578-11ea-9992-427ccf41c5ee.png)
3.用户界面格言未显示
![image](https://user-images.githubusercontent.com/50090686/83583969-5e998780-a578-11ea-97e9-a105292a5098.png)
![image](https://user-images.githubusercontent.com/50090686/83583979-66592c00-a578-11ea-92f8-50c7962054de.png)
4.点击该图标时报错
![image](https://user-images.githubusercontent.com/50090686/83584079-a5877d00-a578-11ea-8275-e5af0a815127.png)
5.标记完表情后报这样的错误
![image](https://user-images.githubusercontent.com/50090686/83584182-eed7cc80-a578-11ea-91d9-8c4b35f3131b.png)
6.裁切图片只能以固定长宽比的矩形
![image](https://user-images.githubusercontent.com/50090686/83584402-a66cde80-a579-11ea-84da-499e7398ef49.png)
7.编辑界面的添加文字，添加多个后，前几个添加的不能删除、放大或者缩小
![image](https://user-images.githubusercontent.com/50090686/83584752-9dc8d800-a57a-11ea-9f16-b525935db1d8.png)
8.编辑界面的添加文字，先添加几个文字，再添加文字后直接改变文字颜色，改变的前一个文字的颜色
![image](https://user-images.githubusercontent.com/50090686/83585078-78889980-a57b-11ea-8341-71613cc22402.png)
![image](https://user-images.githubusercontent.com/50090686/83585104-8dfdc380-a57b-11ea-9fdf-67489e65c4a6.png)


以前的：
1.商店部分图片显示不出来
2.轮播模块没有显示出来

**Comment by gzhGit** [comment]
现在的：
1.商店界面搜索用户文本组件“为你推荐”也在搜索表情和自制推荐中显示。
![QQ浏览器截图20200603110137](https://user-images.githubusercontent.com/48408897/83591373-5c402900-a58a-11ea-828d-2de3cf79ac45.png)
以前的：
1.用户经验显示不同步（已解决）。
2.部分图片无法下载（已解决）。
3.点击图片的上传者，用户信息显示错误（已解决）。
4.撤销图片编辑会导致意外错误（已解决）。
5.商店搜索图片弹窗的显示与隐藏逻辑错误（已解决）。
6.点击图片评论信息无法显示（已解决）。
7.图片点赞后没有及时更新点赞次数（已解决）。
8.热搜关键字的搜索次数没有及时更新（已解决）。
9.推荐相似表情显示异常（已解决）。
