### ISSUE TITLE
表情详细页面

### ISSUE THREAD

**Issue by huangjihui511** [huangjihui511/BUAA-2019-Good-Good-Study-Beta#9]
1. 图片
2. 显示图评论，可以留言
3. 相似推荐
4. 收藏编辑下载分享等按钮
5. 显示作者的信息，可以进入作者的页面

**Comment by huangjihui511** [comment]
发现问题
1.  后退地址不对
2. 图片建议使用模版的方法显示
3. 文字部分建议使用模版显示
4. 评论的发送按钮可以集成到功能块中
5. 缺少作者的显示

**Comment by huangjihui511** [comment]
界面方面
1. 顶部没有显示页面的名字
2. 图片没有使用模版，没有居中
3. 转发，保存到手机，修改标签的图标不太合适
4. 评论无法看到用户名
功能方面
1. 推荐表情没有
2. 无法从评论进入用户的页面
3. （似乎）缺少收藏到小程序的按钮

**Comment by huangjihui511** [comment]
商店部分
1. 缺少评论
2. 下载无效
3. 点赞没有反馈，也没有地方可以看到点赞的数量，建议结合模版的labels模版

**Comment by notasadsong** [comment]
1、商店部分表情好像无法评论？（或者是我网卡转圈圈出不来）
2、商店收藏的表情好像还是无法进行编辑，有报错
3、评论的发送按钮能否稍作优化

**Comment by notasadsong** [comment]
1、商店表情评论后退出再进入无评论
2、无法编辑商店收藏的表情
3、主页的表情详情页面无推荐相似表情

**Comment by notasadsong** [comment]
1、最好能把评论的时间显示改简洁一点（年月日时分）
2、推荐表情好像点不进去

**Comment by huangjihui511** [comment]
1. 点赞和收藏次数单独显示
2. 0次的时候显示有问题
